routes/web.php
        Route::get('member_offline_game_record', 'MemberOfflineGameRecordController@index')->name('daili.member_offline_game_record');
        //佣金记录
        Route::get('daili_money_log', 'DailiMoneyLogController@index')->name('daili.daili_money_log');

    });
});

Route::group(['domain' => 'admin.0056u.com', 'prefix' => 'admin','namespace' => 'Admin'],function ($router){

    Route::get('/login', ['as' => 'admin.login','uses' => 'AuthController@getLogin']);
    Route::post('/login', ['as' => 'admin.login.post','uses' => 'AuthController@postLogin']);
    Route::get('/loginOut', ['as' => 'admin.login.out','uses' => 'AuthController@getLoginOut']);
    //需要登录
    Route::group(['middleware' => ['authorize']], function($router){
        //后台首页
        $router->get('/', 'AdminController@index')->name('admin.index');
        $router->get('hk_notice', 'AdminController@hk_notice')->name('admin.hk_notice');
        $router->get('tk_notice', 'AdminController@tk_notice')->name('admin.tk_notice');
        //系统设置
        //个人资料
        Route::resource("user", 'UserController');
        Route::get('personal', ['as' => 'user.personal', 'uses' => 'UserController@getPersonal']);
        Route::post('personal', ['as' => 'user.personal.post', 'uses' => 'UserController@postPersonal']);
        //管理组
        Route::get('role/relation/{id}', ['as' => 'role.relation', 'uses' => 'RoleController@showRelation']);
        Route::post('role/relation/{id}', ['as' => 'role.relation.post', 'uses' => 'RoleController@relation']);
        Route::resource("role", 'RoleController');
        //系统配置
        Route::get('bank_card/check/{id}/{status}', 'BankCardController@check')->name('bank_card.check');
        Route::resource("bank_card", 'BankCardController');
        Route::resource("system_config", 'SystemConfigController');
        Route::resource("black_list_ip", 'BlackListIpController');
        Route::resource("admin_action_money_log", 'AdminActionMoneyLogController');


        //会员管理
        Route::get('member/check/{id}/{status}', 'MemberController@check')->name('member.check');
        Route::get('member/assign/{id}', 'MemberController@assign')->name('member.assign');
        Route::post('member/assign/{id}', 'MemberController@post_assign')->name('member.post_assign');
        //
        Route::get('member/showGameRecordInfo/{id}', 'MemberController@showGameRecordInfo')->name('member.showGameRecordInfo');
        Route::get('member/showRechargeInfo/{id}', 'MemberController@showRechargeInfo')->name('member.showRechargeInfo');
        Route::get('member/showDrawingInfo/{id}', 'MemberController@showDrawingInfo')->name('member.showDrawingInfo');
        Route::get('member/showDividendInfo/{id}', 'MemberController@showDividendInfo')->name('member.showDividendInfo');
        Route::get('member/checkBalance/{id}', 'MemberController@checkBalance')->name('member.checkBalance');
        Route::get('member/showTransfer/{id}', 'MemberController@showTransfer')->name('member.showTransfer');
        Route::resource('member', 'MemberController');
        //红利记录
        Route::resource('dividend', 'DividendController');
        //登录记录
        Route::resource('member_login_log', 'MemberLoginLogController');
        //游戏记录
        Route::resource('game_record', 'GameRecordController');
        //平台转账
        Route::resource('transfer', 'TransferController');


        //返水
        //返水等级
        Route::resource('fs_level', 'FsLevelController');
        Route::resource('send_fs', 'SendFsController');
        Route::resource('fs', 'FsController');


        //代理
        //代理审核
        Route::resource('member_daili_apply', 'MemberDailiApplyController');
        //代理列表
        Route::resource('member_daili', 'MemberDailiController');
        //下线会员
        Route::resource('member_offline', 'MemberOfflineController');
        //下线会员存款记录
        Route::resource('member_offline_recharge', 'MemberOfflineRechargeController');
        //下线会员提款记录
        Route::resource('member_offline_drawing', 'MemberOfflineDrawingController');
        //下线会员红利记录
        Route::resource('member_offline_dividend', 'MemberOfflineDividendController');
        //下线会员输赢记录
        Route::resource('member_offline_game_record', 'MemberOfflineGameRecordController');
        //佣金记录
        Route::get('daili_money_log/show_by_id/{id}', 'DailiMoneyLogController@show_by_id')->name('daili_money_log.show_by_id');
        Route::resource('daili_money_log', 'DailiMoneyLogController');
        //发放佣金
        Route::resource('send_daili_money', 'SendDailiMoneyController');
        //佣金等级
        Route::resource('yj_level', 'YjLevelController');

        //财务
        //充值、存款列表
        //微信
        Route::put('recharge_weixin/confirm/{id}', 'RechargeWeixinController@confirm')->name('recharge_weixin.confirm');//确认汇款成功
        Route::resource('recharge_weixin', 'RechargeWeixinController');
        //支付宝
        Route::put('recharge_ali/confirm/{id}', 'RechargeAliController@confirm')->name('recharge_ali.confirm');//确认汇款成功
        Route::resource('recharge_ali', 'RechargeAliController');
        //银行卡
        Route::put('recharge_bank/confirm/{id}', 'RechargeBankController@confirm')->name('recharge_bank.confirm');//确认汇款成功
        Route::resource('recharge_bank', 'RechargeBankController');

        Route::put('recharge/confirm/{id}', 'RechargeController@confirm')->name('recharge.confirm');//确认汇款成功
        Route::resource('recharge', 'RechargeController');
        //提款
        Route::put('drawing/confirm/{id}', 'DrawingController@confirm')->name('drawing.confirm');//确认提款成功
        Route::resource('drawing', 'DrawingController');
        //活动
        Route::get('activity/check/{id}/{status}', 'ActivityController@check')->name('activity.check');
        Route::resource('activity', 'ActivityController');

        //内容管理
        //系统公告
        Route::get('system_notice/check/{id}/{status}', 'SystemNoticeController@check')->name('system_notice.check');
        Route::resource('system_notice', 'SystemNoticeController');
        Route::resource('message', 'MessageController');
        //平台管理
        //接口列表
        Route::get('api/check/{id}/{status}', 'ApiController@check')->name('api.check');
        Route::resource('api', 'ApiController');
        Route::get('tcg_game_list/check/{id}/{status}', 'TcgGameListController@check')->name('tcg_game_list.check');
        Route::get('tcg_game_list/pull', 'TcgGameListController@pull')->name('tcg_game_list.pull');
        Route::resource('tcg_game_list', 'TcgGameListController');

        Route::get('game_list/check/{id}/{status}', 'GameListController@check')->name('game_list.check');
        Route::get('game_list/pull', 'GameListController@pull')->name('game_list.pull');
        Route::resource('game_list', 'GameListController');


        //反馈
        Route::get('feedback/check/{id}/{status}', 'FeedbackController@check')->name('feedback.check');
        Route::resource('feedback', 'FeedbackController');

    });
});

//APi
Route::group(['namespace' => 'Api'],function ($router){

    //拉取记录页面
    $router->get('api/game_record', 'IndexController@index')->name('api.game_record.index');
    $router->get('ag/game_record', 'AgController@game_record')->name('ag.game_record');
    $router->get('bbin/game_record', 'BbinController@game_record')->name('bbin.game_record');
    $router->get('ab/game_record', 'AbController@game_record')->name('ab.game_record');
    $router->get('pt/game_record', 'PtController@game_record')->name('pt.game_record');
    $router->get('mg/game_record', 'MgController@game_record')->name('mg.game_record');
    $router->get('ttg/game_record', 'TtgController@game_record')->name('ttg.game_record');
    $router->get('ibc/game_record', 'IbcController@game_record')->name('ibc.game_record');
    $router->get('yc/game_record', 'YcController@game_record')->name('yc.game_record');
    $router->get('cg/game_record', 'CgController@game_record')->name('cg.game_record');
    $router->get('sa/game_record', 'SaController@game_record')->name('sa.game_record');
    $router->get('bg/game_record', 'BgController@game_record')->name('bg.game_record');
    $router->get('dt/game_record', 'DtController@game_record')->name('dt.game_record');
    $router->get('hj/game_record', 'HjController@game_record')->name('hj.game_record');
    $router->get('wjs/game_record', 'WjsController@game_record')->name('wjs.game_record');

    $router->get('og/game_record', 'OgController@game_record')->name('og.game_record');
    $router->get('ebet/game_record', 'EbetController@game_record')->name('ebet.game_record');
    $router->get('eg/game_record', 'EgController@game_record')->name('eg.game_record');
    $router->get('eg_3d/game_record', 'EgController@game_record_3d')->name('eg.game_record_3d');
    $router->get('eg_pl3/game_record', 'EgController@game_record_pl3')->name('eg.game_record_pl3');
    $router->get('eg_6hc/game_record', 'EgController@game_record_6hc')->name('eg.game_record_6hc');
    $router->get('ss/game_record', 'SsController@game_record')->name('ss.game_record');
    $router->get('bs/game_record', 'BsController@game_record')->name('bs.game_record');
    $router->get('mw/game_record', 'MwController@game_record')->name('mw.game_record');
    $router->get('png/game_record', 'PngController@game_record')->name('png.game_record');


    Route::group(['middleware' => 'auth.member:member'], function($router){
        //进游戏
        $router->get('ag/playGame', 'AgController@login')->name('ag.playGame');
        $router->get('bbin/playGame', 'BbinController@login')->name('bbin.playGame');
        $router->get('ab/playGame', 'AbController@login')->name('ab.playGame');
        $router->get('pt/playGame', 'PtController@login')->name('pt.playGame');
        $router->get('mg/playGame', 'MgController@login')->name('mg.playGame');
        $router->get('ttg/playGame', 'TtgController@login')->name('ttg.playGame');
        $router->get('ibc/playGame', 'IbcController@login')->name('ibc.playGame');

app/Models/FsLevel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FsLevel extends Model
{
    protected $table = 'fs_level';

    protected $guarded = [];
}

app/Http/Controllers/Admin/FsLevelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\FsLevel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class FsLevelController extends AdminBaseController
{
    public function index(Request $request)
    {
        $mod = new FsLevel();

        $game_type = '';

        if ($request->has('game_type'))
        {
            $game_type = $request->get('game_type');
            $mod = $mod->where('game_type', $game_type);
        }

        $data = $mod->orderBy('level', 'asc')->paginate(config('admin.page-size'));

        return view('admin.fs_level.index', compact('data', 'game_type'));
    }

    public function create()
    {
        return view('admin.fs_level.create');
    }

    public function store(Request $request)
    {
        $validator = $this->verify($request, 'fs_level.store');

        if ($validator->fails())
        {
            $messages = $validator->messages()->toArray();
            return responseWrong($messages);
        }

        $data = $request->all();

        if (FsLevel::where('level', $data['level'])->where('game_type', $data['game_type'])->first())
            return responseWrong('该游戏类型下已存在该等级的返水等级');

        FsLevel::create($data);

        return responseSuccess('', '', route('fs_level.index'));

    }

    public function edit($id)
    {
        $data = FsLevel::findOrFail($id);

        return view('admin.fs_level.edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $validator = $this->verify($request, 'fs_level.store');

        if ($validator->fails())
        {
            $messages = $validator->messages()->toArray();
            return responseWrong($messages);
        }
        $data = $request->all();

        if (FsLevel::where('level', $data['level'])->where('game_type', $data['game_type'])->where('id', '!=', $id)->first())
            return responseWrong('该游戏类型下已存在该等级的返水等级');

        $mod = FsLevel::findOrFail($id);

        $mod->update($data);

        return responseSuccess('', '', route('fs_level.index'));

    }

    public function destroy($id)
    {
        FsLevel::destroy($id);

        return respS();
    }
}

resources/views/admin/fs_level/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <section class="content">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">添加返水等级</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" id="form" action="{{ route('fs_level.store') }}" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="level" class="col-sm-2 control-label">选择返水等级</label>
                            <div class="col-sm-7">
                                <select name="level" id="level" class="form-control">
                                    <option value="">--请选择--</option>
                                    @foreach(range(1, 10) as $v)
                                        <option value="{{ $v }}">{{ $v }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="level" class="col-sm-2 control-label">所属游戏类型</label>
                            <div class="col-sm-7">
                                <select name="game_type" id="game_type" class="form-control">
                                    <option value="">--请选择--</option>
                                    @foreach(config('platform.game_type') as $k => $v)
                                        <option value="{{ $k }}">{{ $v }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">等级名称</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" id="name" name="name" placeholder="例：一星会员" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="quota" class="col-sm-2 control-label">额度</label>
                            <div class="col-sm-7">
                                <input type="number" class="form-control" id="quota" name="quota" placeholder="例：1500" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="rate" class="col-sm-2 control-label">返水比例</label>
                            <div class="col-sm-7">
                                <input type="number" class="form-control" id="rate" name="rate" placeholder="例：1.5" />
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <div class="form-group">
                            <label class="col-sm-2 control-label"></label>
                            <div class="col-sm-7">
                                <button type="button" class="btn btn-primary submit-form-sync">提交</button>
                                &nbsp;<a href="{{ route('fs_level.index') }}" class="btn btn-info">返回</a>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </section><!-- /.content -->
@endsection

resources/views/admin/fs_level/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <section class="content">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">编辑返水等级</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" id="form" action="{{ route('fs_level.update', ['id' => $data->id]) }}" method="post">
                    <input type="hidden" name="_method" value="put">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="level" class="col-sm-2 control-label">选择返水等级</label>
                            <div class="col-sm-7">
                                <select name="level" id="level" class="form-control">
                                    <option value="">--请选择--</option>
                                    @foreach(range(1, 10) as $v)
                                        <option value="{{ $v }}" @if($data->level == $v) selected @endif>{{ $v }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="level" class="col-sm-2 control-label">所属游戏类型</label>
                            <div class="col-sm-7">
                                <select name="game_type" id="game_type" class="form-control">
                                    <option value="">--请选择--</option>
                                    @foreach(config('platform.game_type') as $k => $v)
                                        <option value="{{ $k }}" @if($data->game_type == $k) selected @endif>{{ $v }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">等级名称</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" id="name" name="name" placeholder="例：一星会员" value="{{ $data->name }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="quota" class="col-sm-2 control-label">额度</label>
                            <div class="col-sm-7">
                                <input type="number" class="form-control" id="quota" name="quota" placeholder="例：1500" value="{{ $data->quota }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="rate" class="col-sm-2 control-label">返水比例</label>
                            <div class="col-sm-7">
                                <input type="number" class="form-control" id="rate" name="rate" placeholder="例：1.5" value="{{ $data->rate }}" />
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <div class="form-group">
                            <label class="col-sm-2 control-label"></label>
                            <div class="col-sm-7">
                                <button type="button" class="btn btn-primary submit-form-sync">提交</button>
                                &nbsp;<a href="{{ route('fs_level.index') }}" class="btn btn-info">返回</a>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </section><!-- /.content -->
@endsection

resources/views/admin/fs_level/filter.blade.php
<div class="container-fluid" style="margin-bottom: 10px;">
    <form action="" method="get" id="searchForm">
        <div class="row">
            <div class="col-lg-4">
                <div class="input-group">
                    <span class="input-group-addon">游戏类型</span>
                    <select name="game_type" id="game_type" class="form-control">
                        <option value="">--请选择--</option>
                        @foreach(config('platform.game_type') as $k => $v)
                            <option value="{{ $k }}" @if($game_type == $k) selected @endif>{{ $v }}</option>
                        @endforeach
                    </select>

                </div>
            </div>
            <div class="col-lg-2 pull-right">
                <div class="input-group">
                    <button type="submit" class="btn btn-primary">搜索</button>&nbsp;&nbsp;
                    <a class="btn btn-info" href="{{ route('fs_level.create') }}"><span class="glyphicon glyphicon-plus"></span>添加返水等级</a>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/admin/fs_level/index.blade.php
@extends('admin.layouts.main')
@section('content')
     <section class="content">
         <div class="panel panel-primary">
             <div class="panel-heading">
                 <h3 class="panel-title">返水等级列表</h3>
             </div>
             <div class="panel-body">
                 @include('admin.fs_level.filter')
                 <h3 style="color: red" class="text-center"> 发放返水时会按照返水等级倒序匹配</h3>
                 <table class="table table-bordered table-hover text-center">
                     <tr>
                         <th style="width: 10%">ID</th>
                         <th class="text-center">返水等级</th>
                         <th  style="width: 10%">游戏类型</th>
                         <th  style="width: 20%">等级名称</th>
                         <th  style="width: 20%">额度</th>
                         <th  style="width: 10%">返水比例</th>
                         <th  style="width: 20%">操作</th>
                     </tr>
                     @foreach($data as $item)
                         <tr>
                             <td>
                                 {{ $item->id }}
                             </td>
                             <td>
                                 {{ $item->level }}
                             </td>
                             <td>
                                 {{ config('platform.game_type')[$item->game_type] }}
                             </td>
                             <td>
                                 {{ $item->name }}
                             </td>
                             <td>
                                 {{ $item->quota }}
                             </td>
                             <td>
                                 {{ $item->rate }}%
                             </td>
                             <td>
                                 <a href="{{ route('fs_level.edit', ['id' => $item->getKey()]) }}" class="btn btn-primary btn-xs">修改</a>
                                 <button class="btn btn-danger btn-xs"
                                         data-url="{{route('fs_level.destroy', ['id' => $item->getKey()])}}"
                                         data-toggle="modal"
                                         data-target="#delete-modal"
                                 >
                                     删除
                                 </button>
                             </td>
                         </tr>
                     @endforeach
                 </table>
                 <div class="clearfix">
                     <div class="pull-left" style="margin: 0;">
                         <p>总共 <strong style="color: red">{{ $data->total() }}</strong> 条</p>
                     </div>
                 <div class="pull-right" style="margin: 0;">
                     {!! $data->render() !!}
                 </div>
                 </div>
             </div>
         </div>

     </section><!-- /.content -->
@endsection
@section("after.js")
     @include('admin.layouts.delete',['title'=>'操作提示','content'=>'你确定要删除这个返水等级吗?'])
@endsection